### ISSUE TITLE
Make available via Alcatraz

### ISSUE THREAD

**Issue by mrackwitz** [robertvojta/LigatureXcodePlugin#1]
Could you make that available via [Alcatraz](/supermarin/Alcatraz)?

**Comment by zrzka** [comment]
I will, but later. Now, it's an ugly quick hack affecting all attributed strings. This needs to be fixed. IOW find exact location where `NSLigatureAttributeName` is set to `@0` and replace it with `@1`.

**Comment by zrzka** [comment]
On hold till #2 will be fixed.

**Comment by zrzka** [comment]
<img width="657" alt="screen shot 2015-09-17 at 13 58 52" src="https://cloud.githubusercontent.com/assets/1084172/9932457/54efb3d4-5d44-11e5-9a62-6431275af5f7.png">

Fixed.
