### ISSUE TITLE
Xcode 8.0 Compatibility

### ISSUE THREAD

**Issue by carlossless** [robertvojta/LigatureXcodePlugin#11]
Hi, I guess the title says it all. It would be nice to have this work in Xcode 8.0.

**Comment by shayanbo** [comment]
Plugins haven't been loaded in Xcode8, See [#475](https://github.com/alcatraz/Alcatraz/issues/475) for more information,
the workaround by now is unsign xcode, method and tool is detailed in that thread.

**Comment by zrzka** [comment]
@carlossless / @MickeyHub feel free to create pull request. I do not have Xcode 8 installed yet and not sure when I'll have some time to test mentioned Alcatraz / Xcode unsign workarounds.

**Comment by zrzka** [comment]
@MickeyHub thanks, your PR merged.
