### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by alessandro-molari** [robertvojta/LigatureXcodePlugin#6]
I've installed the plugin in Alcatraz, loaded it and enabled default ligatures.

However when I type signs that should be converted into ligatures, they won't.

Are there additional steps to enable this plugin?

**Comment by zrzka** [comment]
No other steps are required. Do you have font which supports ligatures? Xcode - Preferences - Font & Colors.

**Comment by alessandro-molari** [comment]
I'm using Menlo

**Comment by zrzka** [comment]
Did add font requirements description. I'm sorry, but Menlo doesn't support ligatures and it will not work for you. You have to install font with ligatures support. Like mentioned [PragmataPro](http://www.fsd.it/fonts/pragmatapro.htm#.VjSznYRIi34) made by @fabrizioschiavi.

**Comment by alessandro-molari** [comment]
Ah ok, thanks very much :smile:
