### ISSUE TITLE
Xcode Version 7.1.1 (7B1005) - installs via Alcatraz, but no ligatures work.

### ISSUE THREAD

**Issue by benjamin-rood** [robertvojta/LigatureXcodePlugin#7]
It installs fine, on restart of Xcode it asks if you are sure you want to load LigatureXcodePlugin, which of course you say 'Load', and you see Edit>'Ligature plug in' but no typed ligatures work.

Obviously this is a beta version so I am sure that is why it isn't working, but I just thought I would bring it to your attention.

Thanks!

**Comment by zrzka** [comment]
Thanks for you report @benjamin-rood! Are you sure that you have installed (and using) font with ligatures? Isn't your problem font related like - #6 _Doesn't work for me_?

**Comment by benjamin-rood** [comment]
Hi Robert, yes, the fonts are installed correctly. But oh crap, I just realised I didn't change the Font in the editor! Forget about this, it is seems like it is working 100% fine!

Argh! Sorry!!!!

**Comment by zrzka** [comment]
If fonts are okay and you're using font with ligatures support (_Xcode - Preferences... - Fonts & Colors_), any other Xcode plug-ins installed? Can imagine some of these plug-ins can interfere. If yes, can you put a list of them here?

**Comment by benjamin-rood** [comment]
Sorry Robert, please delete this issue entirely, it was my own lazy oversight to not chose a font with ligature support!

**Comment by zrzka** [comment]
Don't worry, glad it works and it was just some font issue ;-) Anyway, thanks for reporting it. Going to update README, because I do receive similar "questions" / "reports" regularly.
